-- PAISES ingresados 

INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (1, 'Honduras');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (2, 'México');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (3, 'Guatemala');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (4, 'El Salvador');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (5, 'Nicaragua');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (6, 'Costa Rica');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (7, 'Panamá');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (8, 'Colombia');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (9, 'Venezuela');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (10, 'Perú');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (11, 'Chile');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (12, 'Argentina');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (13, 'Brasil');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (14, 'Paraguay');
INSERT INTO PAISES (ID_PAIS, NOMBRE) VALUES (15, 'Uruguay');

COMMIT;

